spring:
  application:
    name: safehome
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-redis.yml
      - classpath:application-swagger.yml
      - classpath:application-websocket.yml
      - classpath:application-logging.yml
      - classpath:application-ai.yml
      - classpath:application-notification.yml
      - classpath:application-sentry.yml
      - classpath:application-auth.yml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
